version: '3.2'
services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
    - "6379:6379"
    networks:
    - md_network
  was:
    container_name: MyMock
    build:
      context: .
    ports:
    - "7001:7001"
    networks:
    - md_network
networks:
  md_network: