version: '3.2'
services:
  redis:
    image: "redis:alpine"
    hostname: redis
    networks:
    - md_network
  was:
    build:
      context: .
    ports:
    ##PORTS
    links:
    - redis
    environment:
    - REDIS_URL=redis
    networks:
    - md_network
  docu:
    build:
      context: .
      dockerfile: Dockerfile-docu
    ports:
    - 8642:8642
networks:
  md_network: