name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Setup node JS
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    # Clone repo
    - uses: actions/checkout@v2

    # Install project
    - name: Install application
      run: |
        cd src
        npm install

    # Add right to wait shell script
    - name: Execute integration tests
      run: |
        cd src
        chmod +x wait
        
    - name: Build site assets
      working-directory: ${{ github.workspace }}
      run: ls -la
      
    - name: Build site assets
      working-directory: ${{ github.workspace }}/src
      run: ls -la

    # Artifact result
    - uses: kevinramage/runVenomTests@c1b4f4500a96fa97ac815ec3535878e41ca172a6
      working-directory: ${{ github.workspace }}/src
      with:
        artifactName: results.xml
        venom_path: ./integration/*.yml
        venom_parallel: "2"
        venom_outputdir: "."