name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Setup node JS
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    # Clone repo
    - uses: actions/checkout@v2

    # Install project
    - name: Install application
      run: |
        cd src
        npm install

    # Add right to wait shell script
    - name: Execute integration tests
      run: |
        cd src
        chmod +x wait

    # Artifact result
    - uses: kevinramage/runVenomTests@efc9295f70a3c60a269dd8f2bf7454f1960893b7
      with:
        workspace: src
        artifactName: results.xml
        venom_path: ./integration/*.yml
        venom_parallel: "2"
        venom_outputdir: "."