name: CI

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:

    # Setup node JS
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    # Clone repo
    - uses: actions/checkout@v2

    # Install project
    - name: Install application
      run: |
        npm install

    # Add right to wait shell script
    - name: Execute integration tests
      run: |
        chmod +x wait
        
    - name: Build site assets
      run: ls -la

    # Artifact result
    - uses: kevinramage/runVenomTests@6a2b1b342f2558664cf9660b0f0f4e67cfe272e8
      with:
        workingDirectory: src
        artifactName: results.xml
        venom_path: ./integration/*.yml
        venom_parallel: "2"
        venom_outputdir: "."