name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Setup node JS
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    # Clone repo
    - uses: actions/checkout@v2

    # Install project
    - name: Install application
      run: |
        cd src
        npm install

    # Download venom executable
    - name: Download venom executable
      run: |
        cd src/integration
        chmod +x downloadVenom.sh
        ./downloadVenom.sh

    # Execute integration tests
    - name: Execute integration tests
      run: |
        cd src
        chmod +x integration/venom.linux-amd64
        chmod +x wait
        ./integration/venom.linux-amd64 run --log debug --parallel 2 --output-dir . ./integration/*.yml

    # Artifact result
    - uses: actions/upload-artifact@v2
      with:
        name: test_results
        path: src/test_results.xml

    # Proceed report
    - name: AnalyzeReport
      run: |
        RETURN_CODE=$(cat src/test_results.xml | grep "<failure>" | wc -l)
        echo $RETURN_CODE
        exit $RETURN_CODE